# Generated by Django 6.0.5 on 2026-05-12 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order'], 'verbose_name': 'Пример работы (портфолио)', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='tag',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
