# Generated by Django 6.0.5 on 2026-05-12 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_portfolio_year_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('letters', 'Объёмные буквы'), ('box', 'Световые короба'), ('light', 'Лайтбоксы'), ('banner', 'Баннеры'), ('pylon', 'Стелы'), ('transport', 'Транспорт'), ('roof', 'Крышные установки')], max_length=40, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='hue',
            field=models.PositiveSmallIntegerField(help_text='Число от 0 до 360 — цвет декоративной подсветки карточки.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Оттенок подсветки'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='item_id',
            field=models.CharField(help_text='Короткий номер для отображения, например 01.', max_length=8, unique=True, verbose_name='Код карточки'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Чем меньше число, тем выше карточка на сайте.', unique=True, verbose_name='Порядок в списке'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото работы для карточки в портфолио (необязательно).', null=True, upload_to='portfolio/%Y/%m/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='span',
            field=models.JSONField(default=list, help_text='Два числа: ширина и высота в ячейках, например [6, 3].', verbose_name='Размер в сетке'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='spot',
            field=models.CharField(help_text='Адрес, торговый центр или краткая подпись под названием.', max_length=200, verbose_name='Место / описание локации'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='tag',
            field=models.CharField(blank=True, help_text='Обычно год (например 2024). Можно оставить пустым.', max_length=40, verbose_name='Метка на карточке'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выполнения'),
        ),
    ]
